CustomerOrder:
    type: entity
    table: customer_order
    id:
        idorder:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        idclient:
            type: integer
            nullable: false
            options:
                unsigned: false
        date:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
